### ISSUE TITLE
Barra de progreso

### ISSUE THREAD

**Issue by GandyA23** [OMRI-Tech/FE-omri-app#30]

**Comment by pronficilio** [comment]
![image](https://user-images.githubusercontent.com/4611904/175060974-a8f9ddcc-1c0d-4108-8c93-eefa03e926fe.png)

![image](https://user-images.githubusercontent.com/4611904/175061025-57613ca4-31d2-4132-8570-34c398009823.png)


Para acercar más la barra de progreso al diseño, cambiemos el color del resto de la barra con un estilo en **.q-linear-progress__track**

```
background: #7B7B7B;
opacity: 1;
```

para que quede así:
![image](https://user-images.githubusercontent.com/4611904/175062052-ab858b67-a126-425f-adb9-40943cb7cfc1.png)

También incluyamos la sombra interna en **.q-linear-progress__track**

`box-shadow: inset 0px 3.2px 3.2px rgba(0, 0, 0, 0.25);`

Y la externa en **q-linear-progress**

`box-shadow: 0px 3.2px 3.2px rgba(0, 0, 0, 0.25);`

Resultado final:
![image](https://user-images.githubusercontent.com/4611904/175063644-de538943-0da6-47c9-a64d-0ae81b46b0cd.png)

**Comment by pronficilio** [comment]
Bellísimo
