### ISSUE TITLE
Entrenator

### ISSUE THREAD

**Issue by GandyA23** [OMRI-Tech/FE-omri-app#31]

**Comment by pronficilio** [comment]
![image](https://user-images.githubusercontent.com/4611904/175064159-7bd981d1-f941-407d-9343-ef08b2c7475b.png)

El entrenator no toca la parte de abajo del rectángulo como en los diseños

![image](https://user-images.githubusercontent.com/4611904/175064245-dbb3601a-df1c-4e56-ab1c-b88764ae3a05.png)

¿Lo podemos corregir?

**Comment by pronficilio** [comment]
![image](https://user-images.githubusercontent.com/4611904/175414201-76ce5c68-783f-455e-9e19-c4247a0549e7.png)

Entrenator ahora se sale de la caja azul en ciertas resoluciones 😢
